### PR TITLE
Added ability to play a sound when the compilation halts or finishes

### PR DESCRIPTION
**Pull request by magneto538**

### CODE REVIEW

**Comment by magneto538** [comment]
One thing that could be improved is at line 1399 in ksp_compiler.py. There should be a better way to query the /sounds folder without using the parent folder. Since the devs might have different names for the parent folder (e.g. if they pull sKSP via PackageControl vs if they pull it from GitHub), we should change the path in os.path.join to be relative to /sounds. I'm not sure how to do this and have little time to look into it, so in my commit the parent folder must be "KSP (Kontakt Script Processor)" in order for the sounds to play.

**Comment by pryzmusic** [comment]
Hi @magneto538,

I'm confused, where are the sound files? The only change in your commit is the ksp_compiler.py. There is no sound directory nor files included.

**Comment by magneto538** [comment]
Hi @pryzmusic,

You have already merged the /sounds directory with the previous commit. I can see it in the root directory of this repo.

**Comment by pryzmusic** [comment]
Hi @magneto538,

There is no definition for the function "SOUNDS_DIR_PATH()" and as such I can not compile anything.

image

**Comment by magneto538** [comment]
That was a typo from an older version. I've removed those two lines and should be working now.

**Comment by pryzmusic** [comment]
There is a design issue here, which is a dependency on Sublime and OS utilities inside the compiler itself.

The compiler is not supposed to have any concept of Sublime or the OS, as it can be run standalone such as in the command-line.

I will re-fit your play-sound code to instead function inside the ksp_plugin.py, which is the actual code for the Sublime plug-in version of the KSP compiler.

**Comment by magneto538** [comment]
Sounds good. I hadn't thought about that and since the Mac version was working in Sublime Text I didn't investigate further. Thanks!

**Comment by pryzmusic** [comment]
Hi @magneto538,

Since this is a branch from your own repository, I can not update the pull request with new code directly. I will be closing this pull request and creating a new one with the updated commits.

**Pull request closed without merging**
