### PR TITLE
user functions

### PR DESCRIPTION
**Pull request by Levitanus**

### CODE REVIEW

**Comment by Levitanus** [comment]
Have I fix something to pass?

**Comment by neblix** [comment]
I may merge this in at a later point when I have some time to revise it. However, as it stands, the code is somewhat poor quality. There's a lot of evidence that you don't have a lot of python experience, such as when you write loops like:

```python
for i in range(0, len(list)):
    item = list[i]```

instead of simply 

```python
for item in list:```

However, that isn't to say this isn't a great addition and your approach is wrong. It is a useful thing. I don't think many people will be using it often because not many KSP developers know python, so I don't think it's a problem if we wait a little bit.

**Comment by Levitanus** [comment]
Yep, I'm sorry for my style (it's about couple of week i opened the python ref). Especially at the tests and documentation point (just yesterday opened PyDoc for myself).
And of course there is not problem about waiting. Just wanted to know if there are things to do for passing the request.

**Comment by neblix** [comment]
Not to worry. I will handle editing the code before merging it in. Good job on this!

**Comment by Levitanus** [comment]
Forgive me offtopic question, but it's at some point, relative to the subject:
Now, being developing for the new architecture i need to restart sublime every time i want to compile script, if changes were made inside the py packages. Often i load kontakt or logviewer instead sublime and it sucks.
Is the way to reload all modules inside ksp package at the hotkey or at the f5 command?

**Comment by neblix** [comment]
You don't need to restart Sublime when you change the py files. It will run the new ones if you save the new ones.

**Comment by Levitanus** [comment]
the matter is - nope)
I'm not sure, but it seems, that the matter is in fact, that python is not being restarted with f5 command, just runs the compiler modules. And, as python is being interpreting one session whole the time - modules are not being imported again, but used old ones

**Comment by neblix** [comment]
I would just recommend reinstalling Sublime.

**Comment by Levitanus** [comment]
just for fun installed automatic package reloader and put empty KSP.build to the sublime-package archive.
It works :)

**Comment by Levitanus** [comment]
Well, going on:
I'm adding global array, to store IDs of all declared controls:

    on init 
	    declare ui_slider Slider5_6.7 (100, 200)

becomes

    on init
      declare $concat_it
      declare $concat_offset
      declare $string_it
      declare $list_it
      declare %_KF_controls_pull[24]
      declare $_KF_UI_i
      declare %_KF_control_types[13] := (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
      declare const $_KF_control_types__SIZE := 13
      declare ui_slider $Slider5_6__7(100, 200) 
      %_KF_controls_pull[3] := get_ui_id($Slider5_6__7)

but if declaration is inside the module with namespace i get an expected error.

First of all i've tried to `lineObj.namespaces.clean()` and got the error 'control is not declared'.
Then i've add namespace manually, just as i would do with the normal compiler:

    newLines.append(lines[i].copy('_KF_controls_pull[_KF_ControlID'+ str(count-1) +'] := get_ui_id('+self.AddNamespaces(lines[i])+curr_control_name+')'))
    lines[i].namespaces.clear()

and the same error but for the `module.Slider5_6.7`

Then i've looked for solution inside the `ksp_compiler.py` and found many of global vars :D. Where can i place my ui variable to be recognized by compiler?

**Comment by Levitanus** [comment]
well, i think this is an problem to think of:

raised when i thought about concat, which should solve my problems))

**Comment by neblix** [comment]
Levitanus, please avoid asking these questions here. I have no idea what you're trying to do. If you want help trying to figure out how to manipulate the compiler, please feel free to send me an email, but I'm often busy and can't spend a lot of time helping. You can also contact Sam Windell and see if he has any pointers.

**Pull request closed without merging**
