### PR TITLE
Big additions to the extended syntax.

### PR DESCRIPTION
**Pull request by SamWindell**
Added a whole load of preprocessor functions to the compiler that extend the syntax of the language. They should also thrown useful error messages if the KSP file has errors when you hit compile. I've added the details of each feature to the readme.

### CODE REVIEW

**Comment by nojanath** [comment]
This is brilliant.  The PR is rather large so it's taking me some time to get through it all but I like what I've seen.  activate_logger is awesome.

**Comment by SamWindell** [comment]
That's great! Let me know if you have any suggestions/feedback for these features.

**Comment by nojanath** [comment]
I like the fact that all of these additions are optional and none of the core functionality is changed.  I guess the one exception to that is the comment shortcut in Sublime.  However I prefer a prefix for a single line comment instead of wrapping a line in {}.  I think others will welcome that change too.

Nice work!

**Comment by SamWindell** [comment]
I think we've got some good improvements here, I'm already finding this package very useful. 

I was thinking, do you think that this package should have a slightly different name to distinguish it from the original compiler? Or perhaps it will be fine without.

**Comment by nojanath** [comment]
Funny you should ask. I've been conflicted about the name since starting this.  The Package Control folks don't want you to have Sublime in the name so I didn't call it SublimeKSP there.  I decided to go for something easy to search, hence the generic name of KSP (Kontakt Script Processor). Then only the repo is called SublimeKSP which most people might never look at.  I'm definitely open to naming suggestions but I'm ok with it for now...I think.

By the way, I'll have a new tag up with your changes in it shortly.  I wanted to get some documentation in place first.

**Comment by SamWindell** [comment]
Actually, thinking about it, that is probably the best name for it. All of the extra syntax is optional, so it doesn't make sense give a 'programming language' type name as it can be used just as a text editor for native Kontakt script as well. And being KSP that matches the file extension, which is something you wouldn't want to change just to give it a new name!

**Pull request merged**
